on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: windows-latest
    steps:
      - run: Get-DisplayResolution
      - run: Set-DisplayResolution -Width 1920 -Height 1080 -Force
      - run: Get-DisplayResolution
